package com.liecoti.app.localization

import androidx.compose.runtime.*

enum class Language(val code: String, val displayName: String) {
    RU("ru", "Русский"),
    EN("en", "English"),
    PL("pl", "Polski"),
    DE("de", "Deutsch"),
    TR("tr", "Türkçe")
}

data class Strings(
    val appTitle: String,
    val start: String,
    val firmwares: String,
    val engineeringFirmwares: String,
    val standardFirmwares: String,
    val recovery: String,
    val files: String,
    val instructions: String,
    val admin: String,
    val search: String,
    val language: String,
    val download: String,
    val version: String,
    val size: String,
    val date: String,
    val device: String,
    val description: String,
    val password: String,
    val enterPassword: String,
    val cancel: String,
    val confirm: String,
    val addFirmware: String,
    val addRecovery: String,
    val addFile: String,
    val name: String,
    val url: String,
    val notes: String,
    val save: String,
    val delete: String,
    val edit: String,
    val emptyEngineering: String,
    val emptyRecovery: String,
    val emptyFiles: String,
    val copyright: String,
    val welcomeTitle: String,
    val welcomeSubtitle: String
)

private val stringsRu = Strings(
    appTitle = "LIECOTI",
    start = "Начать",
    firmwares = "Прошивки",
    engineeringFirmwares = "Инженерные прошивки",
    standardFirmwares = "Стандартные прошивки",
    recovery = "Recovery",
    files = "Файлы",
    instructions = "Инструкции",
    admin = "Панель управления",
    search = "Поиск",
    language = "Язык",
    download = "Скачать",
    version = "Версия",
    size = "Размер",
    date = "Дата",
    device = "Устройство",
    description = "Описание",
    password = "Пароль",
    enterPassword = "Введите пароль",
    cancel = "Отмена",
    confirm = "Подтвердить",
    addFirmware = "Добавить прошивку",
    addRecovery = "Добавить Recovery",
    addFile = "Добавить файл",
    name = "Название",
    url = "URL",
    notes = "Заметки",
    save = "Сохранить",
    delete = "Удалить",
    edit = "Редактировать",
    emptyEngineering = "Инженерные прошивки скоро появятся",
    emptyRecovery = "Recovery файлы скоро появятся",
    emptyFiles = "Файлы скоро появятся",
    copyright = "© 2026 LIECOTI",
    welcomeTitle = "LIECOTI",
    welcomeSubtitle = "Платформа для прошивок и утилит"
)

private val stringsEn = Strings(
    appTitle = "LIECOTI",
    start = "Start",
    firmwares = "Firmwares",
    engineeringFirmwares = "Engineering Firmwares",
    standardFirmwares = "Standard Firmwares",
    recovery = "Recovery",
    files = "Files",
    instructions = "Instructions",
    admin = "Admin Panel",
    search = "Search",
    language = "Language",
    download = "Download",
    version = "Version",
    size = "Size",
    date = "Date",
    device = "Device",
    description = "Description",
    password = "Password",
    enterPassword = "Enter password",
    cancel = "Cancel",
    confirm = "Confirm",
    addFirmware = "Add Firmware",
    addRecovery = "Add Recovery",
    addFile = "Add File",
    name = "Name",
    url = "URL",
    notes = "Notes",
    save = "Save",
    delete = "Delete",
    edit = "Edit",
    emptyEngineering = "Engineering firmwares coming soon",
    emptyRecovery = "Recovery files coming soon",
    emptyFiles = "Files coming soon",
    copyright = "© 2026 LIECOTI",
    welcomeTitle = "LIECOTI",
    welcomeSubtitle = "Platform for firmware and utilities"
)

private val stringsPl = Strings(
    appTitle = "LIECOTI",
    start = "Start",
    firmwares = "Firmware",
    engineeringFirmwares = "Firmware inżynierskie",
    standardFirmwares = "Firmware standardowe",
    recovery = "Recovery",
    files = "Pliki",
    instructions = "Instrukcje",
    admin = "Panel administracyjny",
    search = "Szukaj",
    language = "Język",
    download = "Pobierz",
    version = "Wersja",
    size = "Rozmiar",
    date = "Data",
    device = "Urządzenie",
    description = "Opis",
    password = "Hasło",
    enterPassword = "Wprowadź hasło",
    cancel = "Anuluj",
    confirm = "Potwierdź",
    addFirmware = "Dodaj firmware",
    addRecovery = "Dodaj Recovery",
    addFile = "Dodaj plik",
    name = "Nazwa",
    url = "URL",
    notes = "Notatki",
    save = "Zapisz",
    delete = "Usuń",
    edit = "Edytuj",
    emptyEngineering = "Firmware inżynierskie wkrótce",
    emptyRecovery = "Pliki Recovery wkrótce",
    emptyFiles = "Pliki wkrótce",
    copyright = "© 2026 LIECOTI",
    welcomeTitle = "LIECOTI",
    welcomeSubtitle = "Platforma firmware i narzędzi"
)

private val stringsDe = Strings(
    appTitle = "LIECOTI",
    start = "Starten",
    firmwares = "Firmwares",
    engineeringFirmwares = "Ingenieurfirmwares",
    standardFirmwares = "Standard-Firmwares",
    recovery = "Recovery",
    files = "Dateien",
    instructions = "Anleitungen",
    admin = "Admin-Panel",
    search = "Suchen",
    language = "Sprache",
    download = "Herunterladen",
    version = "Version",
    size = "Größe",
    date = "Datum",
    device = "Gerät",
    description = "Beschreibung",
    password = "Passwort",
    enterPassword = "Passwort eingeben",
    cancel = "Abbrechen",
    confirm = "Bestätigen",
    addFirmware = "Firmware hinzufügen",
    addRecovery = "Recovery hinzufügen",
    addFile = "Datei hinzufügen",
    name = "Name",
    url = "URL",
    notes = "Notizen",
    save = "Speichern",
    delete = "Löschen",
    edit = "Bearbeiten",
    emptyEngineering = "Ingenieurfirmwares kommen bald",
    emptyRecovery = "Recovery-Dateien kommen bald",
    emptyFiles = "Dateien kommen bald",
    copyright = "© 2026 LIECOTI",
    welcomeTitle = "LIECOTI",
    welcomeSubtitle = "Plattform für Firmware und Dienstprogramme"
)

private val stringsTr = Strings(
    appTitle = "LIECOTI",
    start = "Başlat",
    firmwares = "Firmware'lar",
    engineeringFirmwares = "Mühendislik Firmware'ları",
    standardFirmwares = "Standart Firmware'lar",
    recovery = "Recovery",
    files = "Dosyalar",
    instructions = "Talimatlar",
    admin = "Yönetici Paneli",
    search = "Ara",
    language = "Dil",
    download = "İndir",
    version = "Sürüm",
    size = "Boyut",
    date = "Tarih",
    device = "Cihaz",
    description = "Açıklama",
    password = "Şifre",
    enterPassword = "Şifre girin",
    cancel = "İptal",
    confirm = "Onayla",
    addFirmware = "Firmware Ekle",
    addRecovery = "Recovery Ekle",
    addFile = "Dosya Ekle",
    name = "Ad",
    url = "URL",
    notes = "Notlar",
    save = "Kaydet",
    delete = "Sil",
    edit = "Düzenle",
    emptyEngineering = "Mühendislik firmware'ları yakında",
    emptyRecovery = "Recovery dosyaları yakında",
    emptyFiles = "Dosyalar yakında",
    copyright = "© 2026 LIECOTI",
    welcomeTitle = "LIECOTI",
    welcomeSubtitle = "Firmware ve araçlar platformu"
)

object Localization {
    private val stringsMap = mapOf(
        Language.RU to stringsRu,
        Language.EN to stringsEn,
        Language.PL to stringsPl,
        Language.DE to stringsDe,
        Language.TR to stringsTr
    )

    @Composable
    fun current(): Strings {
        val language = LocalLanguage.current
        return stringsMap[language] ?: stringsRu
    }
}

val LocalLanguage = staticCompositionLocalOf { Language.RU }
